### ISSUE TITLE
unwanted refresh/reload of site on GCP

### ISSUE THREAD

**Issue by shimbalama** [shimbalama/omics_dashboard#17]
Page randomly refreshes/resets while navigating

**Comment by simonfoster806** [comment]
no idea what triggers it, but it happens regularly (every minute or 2)

**Comment by shimbalama** [comment]
https://community.plotly.com/t/why-is-my-reload-hash-constantly-firing-in-debug-false-mode/70468

**Comment by shimbalama** [comment]
turned off debug
