### ISSUE TITLE
Names for Mills 2021 RNA-seq

### ISSUE THREAD

**Issue by Huddo-max** [shimbalama/omics_dashboard#18]
CTRL is fine
CoVB - change to SARS-CoV-2 with DMSO
CoVA - change to SARS-CoV-2 with INCB054329

**Comment by shimbalama** [comment]
ok

**Comment by simonfoster806** [comment]
Could we add a description below the title to indicate the model (ie in mouse or hCO) and the treatments (with concentration and time)?

**Comment by shimbalama** [comment]
these changes are just made in input files. and Simon, yes, doco coming
