### ISSUE TITLE
BENO phosphoproteomics dataset

### ISSUE THREAD

**Issue by SamN1985** [shimbalama/omics_dashboard#22]
Hi - just querying this dataset. We have BENOs and mgBENOs but no storm/control condition. 
Thanks.

**Comment by shimbalama** [comment]
Thanks Sam, this is due to the POR (point of reference) issue. Will be resolved and you your data will be added, too.

**Comment by shimbalama** [comment]
given the decision to exclude stat from any dataset with multiple POR this was easy, no code change just column name change from cd, beno to cs-beno etc (comma is a common delineator)
