### ISSUE TITLE
Proteomics and phosphoproteomics datasets

### ISSUE THREAD

**Issue by simonfoster806** [shimbalama/omics_dashboard#24]
Hi Liam
Harley and I are looking onto phospho and proteomics datasets and have suggestions. Not sure how practical/easy/impossible to do... happy to chat further!
ISSUES
- p values values show up as zero in proteomics data (need to be removed)
- stats bars at top need to be removed from plots (they are confusing...and all zeros anyway)
- y axes for proteomics should be 'Protein abundance'
- x axes for proteomics should be 'Condition'

- y axes for phosphoproteomics should be 'Phosphopeptide abundance'
- x axes for phosphoproteomics should be 'Phosphopeptide'
- Legend label for phosphoproteomics should be 'Condition'
- we tried titin (TTN) knowing that it has heaps of phosphosites - it melted the dashboard. oops. not sure what to suggest here? maybe a maximum entry cutoff? (the dashboard is not loading now...)

SUGGESTIONS:
 - could we toggle between abundance values and log10(abundance) values for both proteomics and phospho?

**Comment by shimbalama** [comment]
p values values show up as zero in proteomics data (need to be removed) - yes if no data, but keep if data isn't significant
stats bars at top need to be removed from plots (they are confusing...and all zeros anyway) - no, keep (make toggle)

all axes/legend - yes

could we toggle between abundance values and log10(abundance) values for both proteomics and phospho? - yes

**Comment by shimbalama** [comment]
done, with a compromises...
