### ISSUE TITLE
RNAseq dataset suggestions

### ISSUE THREAD

**Issue by simonfoster806** [shimbalama/omics_dashboard#25]
Hi Liam
A couple of suggestions for the RNAseq data:

- For volcano plots (which look awesome!) is it possible to have a numerical value (possibly hover) for the p value slider? it will make it easier to see what the parameters are set to
- 'Effect size' might need to be specified. Is it log2 fold change?

- it would also be really helpful to add descriptors for all experiments/datasets (this was planned I think?)

Thank you!!

**Comment by shimbalama** [comment]
For volcano plots (which look awesome!) is it possible to have a numerical value (possibly hover) for the p value slider? it will make it easier to see what the parameters are set to - yes

Effect size' might need to be specified. Is it log2 fold change? - yes

it would also be really helpful to add descriptors for all experiments/datasets (this was planned I think?) - yes

**Comment by shimbalama** [comment]
just need doco from the team
