### ISSUE TITLE
Functional data

### ISSUE THREAD

**Issue by simonfoster806** [shimbalama/omics_dashboard#26]
Hi Liam

For the functional data, a few suggestions:
- is it possible to select an experiment to see which treatments/drugs were tested? at the moment I think the gate keeper for drop down menus is 'Drug' (this could also be changed to treatment)
- if possible, would also be good to have units on the x axes (ie concentration in nM uM or mM)

- just got an error when we were trying to toggle between drugs:
⛑️
Failed component prop type: Invalid component prop `figure` key `props` supplied to Graph. Bad object: { "props": { "children": "No data selected" }, "type": "Div", "namespace": "dash_html_components" } Valid keys: [ "data", "layout", "frames" ]
4:48:22 PM
Failed component prop type: Invalid component prop `figure` key `props` supplied to Graph.
Bad object: {
  "props": {
    "children": "No data selected"
  },
  "type": "Div",
  "namespace": "dash_html_components"
}
Valid keys: [
  "data",
  "layout",
  "frames"
]

**Comment by shimbalama** [comment]
is it possible to select an experiment to see which treatments/drugs were tested? at the moment I think the gate keeper for drop down menus is 'Drug' (this could also be changed to treatment) - no

if possible, would also be good to have units on the x axes (ie concentration in nM uM or mM) - yes (just hard code)
